[tool.poetry]
name = "statute-utils"
version = "0.0.5"
description = "Helper functions for statutory processing."
authors = ["Marcelino G. Veloso III <mars@veloso.one>"]

[tool.poetry.dependencies]
python = "^3.10"
text-gists = "^0.0.1"
types-PyYAML = "^6.0.12"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.12.1"
mypy = "^0.981"
black = "^22.10.0"
isort = "^5.10.1"
pre-commit = "^2.19"
ipykernel = "^6.15"
tqdm = "^4.64"
jupyter = "^1.0.0"
notebook = "^6.4.12"

[tool.pytest]
minversion = "7.1"
testpaths = ["tests"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = 'True'

[tool.black]
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''


[build-system]
requires = ["poetry-core>=1.1.12"]
build-backend = "poetry.core.masonry.api"
