[project]
name = "spyglass-py"
version = "0.0.1"
authors = [
  { name="Tyler Julian", email="tyler@spyglass.software" },
]
description = "Spyglass python library."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://spyglass.software"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
