[tool.poetry]
name = "shared_dependencies"
version = "0.1.38"
description = ""
authors = ["Jean-Charles Bouchaud <jeancharles-b@evidenceb.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
httpx = "^0.21.1"
colorama = "^0.4.4"
sentry-sdk = "^1.5.1"
pure-eval = "^0.2.1"
executing = "^0.8.2"
asttokens = "^2.0.5"
pydantic = {extras = ["dotenv"], version = "^1.9.0"}
PyJWT = "^2.3.0"
pycrypto = "^2.6.1"
cryptography = "^36.0.1"
tenacity = "^8.0.1"
redis = "^4.2.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-httpx = "^0.17.3"
python-dotenv = "^0.19.2"
pytest-annotate = "^1.0.4"
black = "^21.12b0"
flake8 = "^4.0.1"
pre-commit = "^2.17.0"
freezegun = "^1.2.1"
pytest-mock = "^3.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
)/
'''
