[tool.poetry]
name = "dbs"
version = "0.1.1"
description = ""
authors = ["yeger00 <yeger00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
databases = "^0.6.1"
typer = "^0.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
query = "dbs.query:main"
