[tool.poetry]
name = "platts-sdk"
version = "0.3.4"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.1"
black = "^22.10.0"
requests = "^2.28.1"
cachetools = "4.2.4"
pandas = "1.3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
