[tool.poetry]
name = "functions-by-cloudproject"
version = "0.3.0"
description = "This is our test project"
authors = ["Cloud <cloudproject092022@gmail.com>"]
readme = "README.md"
packages = [{include = "functions_by_cloudproject"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
