[tool.coverage.paths]
source=["src","*/site-packages"]

[tool.coverage.run]
branch=true
source=["knada_gsm"]

[tool.coverage.report]
show_missing=true

[tool.poetry]
name = 'knada-gsm'
version = '0.1.0'
description = ""
authors = ["nada <nada@nav.no>"]

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-secret-manager = "^2.12.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
