[tool.poetry]
name = "wf-camera-capture"
version = "1.0.3"
description = "Capture code for rapspi cameras"
authors = ["Paul J DeCoursey <paul@decoursey.net>"]
license = "MIT"
readme = "README.md"
packages = [{include = "capture"}, {include = "cuwb_stream"}]

[tool.poetry.scripts]
wf_capture_tools = 'capture.cli:main'

[tool.poetry.dependencies]
python = "^3.9"
ffmpeg-python = "^0.2.0"
PyYAML = "^6.0"
click = "^8.1.3"
minio = "^7.1.12"
watchdog = "^2.1.9"
pendulum = "^2.1.2"
cachetools = "^5.2.0"
jmespath = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
