[package]
name = "shanten-tools"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "shanten_tools"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.136"
serde_json = "1.0"
lazy_static = "1.4.0"
pyo3 = { version = "0.17", features = ["extension-module"] }
numpy = "0.17"
ndarray = "0.15.0"