[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pypega"
version = "0.0.29"
authors = [
  { name="Rob Smart", email="rob.smart@pega.com" },
]
description = "Python package for orchestrating Pega environments"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "requests-oauthlib >= 1.3.1"
]

[project.urls]
"Homepage" = "https://pypi.org/project/pypega/"